### PR TITLE
Feature/stud 273

### PR DESCRIPTION
**Pull request by car12lin12**
## Description
This PR addresses issue [stud-273](https://team-1610936365889.atlassian.net/browse/STUD-273?atlOrigin=eyJpIjoiNTYwZGE0M2YxN2UyNDQ5N2IxZjg2YzgxMDgzZjYzY2MiLCJwIjoiaiJ9): Add delivery, usecase and repo methods for request to join a team. The following APIs have been implemented:
- **GetChatRoomsByClass:** 
1. user makes a request and provides className for which they want to find teams
2. list of chat rooms is returned

- **JoinRequest:**  

1. user with userID makes a request and provides the roomID for which they want to join ( will check that the room and the user exists )
3. Save a join request message in the message repo for that roomID from userID

#### Join Request in Message repo:

- **RejectJoinRequest:** 

1. The admin of a room can chose to reject the join request, providing the userID to reject and the roomID
2. Conditions: room exists, user rejecting is room admin, student being rejected exists
4. Email is created and sent to rejected student. Currently using mailtrap to see emails.

## Changes to cassandra_chat_schema.cql
- Added **class** attribute to chat.room to enable search room by class: 

- Added **email** to chat.student so we can send rejection email to student: 

## .env Additions

 
You can ask me for team mailtrap account or make your own.

## Testing
Added unit tests for these three methods.
Tested functionality manually using docker and postman.

### CODE REVIEW

**Review by marksman1298 — APPROVED** [review]
Looks good! Great work Carlin 🎆

**Review by nuzurie — COMMENTED** [review]
Can we add a state to participants in the chatroom? For example 'pending' and 'active'. Right now, there is no way to keep track of which user is in what state

**Comment by nuzurie** [comment]
I think a possible way to do this would be to add a tuple instead of user (if allowed by Cassandra), containing the user id and state (could be enum but boolean works since it's just 2 values). This will break a few methods but hopefully unit tests will find the issues

**Comment by car12lin12** [comment]
I think it's better to change students from set of tuples to a [map](https://docs.datastax.com/en/cql-oss/3.1/cql/cql_using/use_map_t.html) to that it's easier to update the user pending status. If it were a set of tuples, there's no easy way to update the user's pending status in fewer steps than with a map. I'd need to find the record for the user's roomID then look for the tuple containing the userID then delete that and add a new tuple that has the updated pending status. Thoughts before I proceed?

**Pull request merged**
